/**
 * Local copies of Figma MAIN / Welcome exports (28:614 / 29:2552 / 49:6785).
 * Paths are public URLs so the static mock page stays backend-free.
 */
export const FIGMA_ASSETS = {
  logo: '/figma/logo-dark.png',
  welcomeMark: '/figma/welcome-mark.png',
  welcomeGlobe: '/figma/welcome-globe.png',
  iconPlus: '/figma/icon-plus.svg',
  iconPlusWhite: '/figma/icon-plus-white.svg',
  iconUpload: '/figma/icon-upload.svg',
  navHome: '/figma/nav-home.svg',
  navRequests: '/figma/nav-requests.svg',
  navEngineers: '/figma/nav-engineers.svg',
  navAlerts: '/figma/nav-alerts.svg',
  navPolicy: '/figma/nav-policy.svg',
  navChats: '/figma/nav-chats.svg',
  navAi: '/figma/nav-ai.svg',
  searchHeader: '/figma/icon-search-header.svg',
  searchPanel: '/figma/icon-search-panel.svg',
  bellHeader: '/figma/icon-bell-header.svg',
  chevronDown: '/figma/icon-chevron-down.svg',
  avatarUser: '/figma/avatar-user.png',
  avatarEngineer: '/figma/avatar-engineer.png',
  map: '/figma/map-moscow.png',
  timeline: '/figma/timeline-track.svg',
  dotEngineers: '/figma/dot-engineers.svg',
  dotMeta: '/figma/dot-meta.svg',
  statusDot: '/figma/status-dot.svg',
  reasonCheck: '/figma/reason-check.svg',
  reasonCar: '/figma/reason-car.svg',
  reasonClock: '/figma/reason-clock.svg',
  reasonPin: '/figma/reason-pin.svg',
  policyArrowClosed: '/figma/policy-arrow-closed.svg',
  policyArrowOpen: '/figma/policy-arrow-open.svg',
  radioEmpty: '/figma/radio-empty.svg',
  radioFilled: '/figma/radio-filled.svg',
  toggleOn: '/figma/toggle-on.svg',
  notifDelay: '/figma/icon-notif-delay.svg',
  notifRoute: '/figma/icon-notif-route.svg',
  notifMessage: '/figma/icon-notif-message.svg',
  arrowRight: '/figma/icon-arrow-right.svg',
  arrowRightWhite: '/figma/icon-arrow-right-white.svg',
  iconArrowCircle: '/figma/icon-arrow-circle.svg',
  iconBack: '/figma/icon-back.svg',
  iconSparkles: '/figma/icon-sparkles.svg',
  toastSystem: '/figma/icon-toast-wrench.svg',
  toastProgress: '/figma/toast-progress-source.png',
  toastAi: '/figma/icon-toast-robot.svg',
  toastChat: '/figma/icon-toast-message.svg',
  toastRoute: '/figma/icon-toast-route.svg',
  toastAlert: '/figma/icon-toast-alert.svg',
  toastClose: '/figma/icon-toast-close.svg',
  toastCloseInk: '/figma/icon-toast-close-ink.svg',
  requestSearchBg: '/figma/icon-request-search-bg.svg',
  requestSearchGlyph: '/figma/icon-request-search-glyph.svg',
  sortChevron: '/figma/icon-sort-chevron.svg',
  statusWork: '/figma/status-dot-work.svg',
  statusAssigned: '/figma/status-dot-assigned.svg',
  statusDone: '/figma/status-dot-done.svg',
  statusUnassigned: '/figma/status-dot-unassigned.svg',
  engPortrait1: '/figma/eng-portrait-1.png',
  engPortrait2: '/figma/eng-portrait-2.png',
  engPortrait3: '/figma/eng-portrait-3.png',
  engEdit: '/figma/icon-eng-edit.svg',
  engTransport: '/figma/icon-eng-transport.svg',
  engOffice: '/figma/icon-eng-office.svg',
  engChat: '/figma/icon-eng-chat.svg',
  engSearch: '/figma/icon-eng-search.svg',
  engDot: '/figma/icon-eng-dot.svg',
} as const;

/** Three Figma portraits cycled on the Engineers ring when the API has no photo. */
export const ENGINEER_PORTRAITS = [
  FIGMA_ASSETS.engPortrait1,
  FIGMA_ASSETS.engPortrait2,
  FIGMA_ASSETS.engPortrait3,
] as const;
